# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 7 Plus",	
  "iPhone 7",
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5"
])

languages([
  "en-US",
  "es-ES"
])

# The name of the scheme which contains the UI Tests
scheme "RGViperChatUITests"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true 

# Choose which project/workspace to use
# project "./RGViperChat.xcodeproj"
workspace "./RGViperChat.xcworkspace"

reinstall_app true

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
